# Generated by Django 2.0.6 on 2019-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empresa_codigomat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='codigoMat',
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigoMat',
            field=models.ManyToManyField(to='app.tipoMaterial'),
        ),
    ]
